export const repMax = [
    {
        id: 1,
        name: 'Взятие в стойку',
        units: 'кг',
        value: 'racking',
        max: 100,
        min: 10,
        defaultValue: 30,
        integer: false,
    },
    {
        id: 2,
        name: 'Становая тяга',
        units: 'кг',
        value: 'deadlift',
        max: 300,
        min: 30,
        defaultValue: 60,
        integer: false,
    },
    {
        id: 3,
        name: 'Жим лёжа',
        units: 'кг',
        value: 'benchpress',
        max: 250,
        min: 20,
        defaultValue: 70,
        integer: false,
    },
    {
        id: 4,
        name: 'Отжимания',
        units: 'раз(а)',
        value: 'pushups',
        max: 100,
        min: 10,
        defaultValue: 30,
        integer: true,
    },
];
